Repository PlaceOS/local, pull requests merged in 2021-12, with the labels that each got.

#88 fix: add empty untracked .env files
  .env.influxdb
  .env.public_key
  .env.secret_key
Labels: type: enhancement

#83 feat(mqtt): add mosquitto container and config
  config/mosquitto/mosquitto.conf
  docker-compose.yml
Labels: type: enhancement, priority: low

#91 Feat/mqtt broker
  config/nginx/bearer.lua
  config/nginx/nginx-nossl.conf
  config/nginx/nginx.conf
  docker-compose.yml
Labels: type: bug
