Repository PlaceOS/local, pull requests merged in 2022-03, with the labels that each got.

#95 refactor: network anchor
  docker-compose.yml
  placeos
  scripts/init-influxdb
  scripts/metricbeat
  scripts/start-services
  scripts/watch-crystal
Labels: type: refactor

#96 release: 1.2203.1
  .env
  .github/workflows/ci.yml
Labels: priority: high, type: maintenance

#99 feat: make analytics and logging stack optional
  .env
  compose-files/metricbeat.yml
  docker-compose.yml
  placeos
  scripts/metricbeat
  scripts/start-services
Labels: focus: devops, type: refactor

#101 fix(docker-compose): add missing service dependency
  docker-compose.yml
  images/service-graph.png
Labels: focus: devops, type: maintenance

#102 feat(docker-compose): add healthchecks to postgres and nginx
  docker-compose.yml
Labels: type: enhancement, focus: devops
