Repository PlaceOS/local, pull requests merged in 2022-05, with the labels that each got.

#119 feat(docker-compose): add otlp header
  .env
  docker-compose.yml
Labels: type: bug, type: maintenance

#120 chore: update to `placeos-1.2205.0`
  .env
  .github/workflows/ci.yml
Labels: type: maintenance

#121 build: update to 1.2205.1
  .env
  .github/workflows/ci.yml
Labels: type: maintenance

#115 fix: no envs
  .env.chronograf
  .env.influxdb
  .env.public_key
  .env.secret_key
  .github/workflows/ci.yml
  placeos
Labels: type: bug, type: enhancement, type: good first issue, priority: low

#125 fix: `docker-compose` env loading in `placeos`
  .env
  .github/workflows/ci.yml
  .github/workflows/update.yml
  docker-compose.yml
  placeos
  scripts/run-init-container
  scripts/run-sam-task
  scripts/shdotenv
Labels: type: bug, type: security, type: refactor

#126 feat: support registry env via `CONTAINER_REGISTRY` var
  .env
  docker-compose.yml
Labels: type: enhancement

#128 fix(docker-compose): use keydb-cli instead of redis-cli in heathcheck
  docker-compose.yml
Labels: type: bug, focus: devops
